name: s6-overlay image builder

env:
  IMAGE: s6-overlay
  NAME: jjrom
  REPO: s6-overlay

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: actuated

    steps:
    # defaults to shallow checkout
    - uses: actions/checkout@v2

    - name: Setup mirror
      uses: self-actuated/hub-mirror@master

    - name: Get TAG
      id: get_tag
      run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

    - name: Print values of all environment variables
      run: printenv
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Release build
      id: release_build
      uses: docker/build-push-action@v4
      with:
        outputs: "type=registry,push=true"
        provenance: false
        platforms: linux/amd64,linux/arm64
        build-args: |
          Version=${{  env.TAG }}
          GitCommit=${{ github.sha }}
        tags: |
          ${NAME}/${IMAGE}:${{ github.sha }}
          ${NAME}/${IMAGE}:${{ env.TAG }}
          ${NAME}/${IMAGE}:latest

      